### ISSUE TITLE
Can't get the plugin to work / How to add episodes?

### ISSUE THREAD

**Issue by AdrianFahrbach** [mauricerenck/kirby-podcaster#16]
Hey there,

I can't get this plugin to work. I get this whenever I try to open the feed:

> Call to a member function podcasterMatomoFeedEnabled() on null

I guess that's because it doesn't find any episodes? If yes, how do I add them?

My current page setup is:

```
kirby/
├── home/
├── contact/
├── [...]
└── podcast/
   ├── feed
   ├── episode-1
```

My "Source Page" is "podcast". I'm using the podcasterfeed blueprint for the feed page and the following blueprint for my episode site:

```
title: Podcast Episode
tabs:
    podcast:
        extends: tabs/podcasterepisode
```

My mp3 file is uploaded to the "podcasterMp3" field within the episode-1 panel.

**Comment by mauricerenck** [comment]
Hey Adrian,

it looks like the plugin isn't able to get the page-object of your feed. Because it doesn't find the feed it fails calling that method on it. The structure itself looks fine to me.

Do you have any other plugins installed, which may listen to `/feed` in a route?

Can you please provide the podcasterfeed.txt/.md file so I can have a look at your settings? You can find it in the `podcast/feed` directory.

What Kirby version are you using? (If you installed via composer, you could do: `composer info` )

**Comment by AdrianFahrbach** [comment]
Thanks for your quick reply!

> Do you have any other plugins installed, which may listen to /feed in a route?

I don't think so. The only plugins installed (other than Kirby-podcaster) are a [markdown-field](https://github.com/sylvainjule/kirby-markdown-field) and a [id3 Kirby plugin](https://github.com/HashandSalt/id3).


> Can you please provide the podcasterfeed.txt/.md file so I can have a look at your settings?

[podcasterfeed.txt](https://github.com/mauricerenck/kirby-podcaster/files/3127880/podcasterfeed.txt)


> What Kirby version are you using?

I'm using 3.0.2.

**Comment by mauricerenck** [comment]
> I'm using 3.0.2.

Okay, I am not sure if that might be the reason, but the plugin uses some features introduced in Kirby 3.1. So if you can, please update your installation. If the error still occurs, I'll try to do a test install locally with your podcasterfeed.txt and try to recreate the error.

**Comment by AdrianFahrbach** [comment]
I upgraded to version 3.1.3 and the error persists :S

**Comment by mauricerenck** [comment]
I just released a new version (1.0.4). Please have a look if this version fixes your issue.

**Comment by AdrianFahrbach** [comment]
Sadly, this didn't fix it for me. I'm still getting the same error.

**Comment by mauricerenck** [comment]
It should work now

**Comment by AdrianFahrbach** [comment]
Its working now! Thank you very much for your support, really appreciate it. Great plugin!
I opened two additional minor issues that I found.
